/**
 * Supabase Service for Nephra
 * 
 * Provides a unified interface for connecting to Supabase
 * and various utility functions for accessing Supabase tables.
 */

import { createClient } from '@supabase/supabase-js';

// Get Supabase credentials from environment variables
const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_KEY || '';

console.log("Initializing Supabase client");

// Create a single Supabase client for the application
export const supabase = createClient(supabaseUrl, supabaseKey);

/**
 * Logs a chat interaction to Supabase
 * 
 * @param userId - The user's ID
 * @param userInput - The message sent by the user
 * @param aiResponse - The response generated by the AI
 * @param model - Optional model name (openai, gemini, etc)
 * @param tags - Optional array of tags/keywords
 * @param metadata - Optional additional data
 * @returns The result from Supabase
 */
export async function logChatToSupabase(
  userId: string | number,
  userInput: string,
  aiResponse: string,
  model: string = 'openai',
  tags: string[] = [],
  metadata: any = {}
) {
  try {
    // Convert number userId to string if needed
    const userIdStr = typeof userId === 'number' ? userId.toString() : userId;
    
    const chatData = {
      user_id: userIdStr,
      user_input: userInput,
      ai_response: aiResponse,
      model_used: model,
      timestamp: new Date().toISOString(),
      tags: tags,
      metadata: metadata
    };
    
    console.log("Logging chat to Supabase:", {
      userId: userIdStr,
      inputLength: userInput.length,
      responseLength: aiResponse.length,
      model,
      tags
    });
    
    const { data, error } = await supabase
      .from('chat_logs')
      .insert([chatData])
      .select();
    
    if (error) {
      console.error("Error logging chat to Supabase:", error.message);
      return { success: false, error };
    }
    
    return { success: true, data };
  } catch (error) {
    console.error("Failed to log chat to Supabase:", error);
    return { success: false, error };
  }
}

/**
 * Gets previous chat history for a user from Supabase
 * 
 * @param userId - The user's ID
 * @param limit - Maximum number of records to return
 * @returns Array of chat interactions
 */
export async function getChatHistoryFromSupabase(
  userId: string | number,
  limit: number = 10
) {
  try {
    // Convert number userId to string if needed
    const userIdStr = typeof userId === 'number' ? userId.toString() : userId;
    
    const { data, error } = await supabase
      .from('chat_logs')
      .select('*')
      .eq('user_id', userIdStr)
      .order('timestamp', { ascending: false })
      .limit(limit);
    
    if (error) {
      console.error("Error getting chat history from Supabase:", error.message);
      return [];
    }
    
    return data || [];
  } catch (error) {
    console.error("Failed to get chat history from Supabase:", error);
    return [];
  }
}

/**
 * Gets health logs for a user from Supabase
 * 
 * @param userId - The user's ID
 * @param limit - Maximum number of records to return
 * @returns Array of health log entries
 */
export async function getHealthLogsFromSupabase(
  userId: string | number,
  limit: number = 20
) {
  try {
    // Convert number userId to string if needed
    const userIdStr = typeof userId === 'number' ? userId.toString() : userId;
    
    const { data, error } = await supabase
      .from('health_logs')
      .select('*')
      .eq('user_id', userIdStr)
      .order('created_at', { ascending: false })
      .limit(limit);
    
    if (error) {
      console.error("Error getting health logs from Supabase:", error.message);
      return [];
    }
    
    return data || [];
  } catch (error) {
    console.error("Failed to get health logs from Supabase:", error);
    return [];
  }
}

/**
 * Saves health data to Supabase
 * 
 * @param healthData - The health data to save
 * @returns Success result and data
 */
export async function saveHealthDataToSupabase(healthData: any) {
  try {
    // Ensure created_at is set if not provided
    if (!healthData.created_at) {
      healthData.created_at = new Date().toISOString();
    }
    
    console.log("Saving health data to Supabase:", healthData);
    
    const { data, error } = await supabase
      .from('health_logs')
      .insert([healthData])
      .select();
    
    if (error) {
      console.error("Error saving health data to Supabase:", error.message);
      return { success: false, error };
    }
    
    return { success: true, data };
  } catch (error) {
    console.error("Failed to save health data to Supabase:", error);
    return { success: false, error };
  }
}

/**
 * Checks if Supabase connection is working
 * 
 * @returns Boolean indicating if connection is successful
 */
export async function checkSupabaseConnection(): Promise<boolean> {
  try {
    // Try to connect to Supabase
    const { error } = await supabase
      .from('chat_logs')
      .select('user_id')
      .limit(1);
    
    if (error) {
      console.warn("Supabase connection check failed:", error.message);
      return false;
    }
    
    console.log("✅ Supabase connection successful");
    return true;
  } catch (error) {
    console.error("Supabase connection error:", error);
    return false;
  }
}