-- Education Articles Table
-- Stores summarized articles from trusted medical sources
CREATE TABLE education_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    url TEXT NOT NULL,
    source TEXT NOT NULL,
    published_date DATE NOT NULL,
    category TEXT NOT NULL,
    user_focus_tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster searching by category
CREATE INDEX idx_education_articles_category ON education_articles (category);

-- Create index for tag-based searching
CREATE INDEX idx_education_articles_tags ON education_articles USING GIN (user_focus_tags);

-- Create view for articles focused on transplants
CREATE VIEW transplant_articles AS
SELECT * FROM education_articles 
WHERE category = 'Transplant' 
   OR 'transplant' = ANY(user_focus_tags);

-- Create view for recent articles (last 30 days)
CREATE VIEW recent_education_articles AS
SELECT * FROM education_articles
WHERE published_date >= (CURRENT_DATE - INTERVAL '30 days');

-- Audit tracking function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Update the updated_at timestamp automatically
CREATE TRIGGER update_education_articles_updated_at
BEFORE UPDATE ON education_articles
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE education_articles IS 'Stores curated educational content for kidney patients from trusted sources';
COMMENT ON COLUMN education_articles.title IS 'Article title';
COMMENT ON COLUMN education_articles.summary IS 'AI-generated plain language summary for patients';
COMMENT ON COLUMN education_articles.url IS 'Original source URL';
COMMENT ON COLUMN education_articles.source IS 'Source organization (CDC, NIDDK, etc)';
COMMENT ON COLUMN education_articles.category IS 'Primary category (Education, Transplant, Diet, etc)';
COMMENT ON COLUMN education_articles.user_focus_tags IS 'Array of tags for focused article retrieval';